### ISSUE TITLE
Do you have a couple of example binary trace dumps to validate?

### ISSUE THREAD

**Issue by g8ecj** [japaric/itm-tools#1]
Both my logic analysers and oscilloscope say my data from an STM32 SWO pin is clean but I'm getting mostly garbage from itm-decode and pcsampl (only about 20% of data seems to be valid. 
I've tried sampling via an ST-Link debugger and directly exporting the logic analyser data but I get the same results with both.
If you could point me at what the data should look like (packet format etc - I've not been able to find it) then I can perhaps I can diagnose my issues

Thanks

**Comment by japaric** [comment]
Hello. You can find the specification of ITM packets in the appendix D4 of [the ARMv7-M Architecture Reference Manual](https://developer.arm.com/documentation/ddi0403/ed) -- I checked the document with ID: ARM DDI 0403E.d (ID070218)

The first thing to check is that you are sampling the data at the right rate. If you have configured the SWO to output data in NRZ format (not manchester encoding) you can read it out using a UART-USB adapter but it needs to be configured to operate at the same frequency as the SWO pin. The SWO frequency (prescaler) is sometimes configurable in a device-specific way (this is the case for the nRF52840). You may want to look into the clock diagram of your device to see which clock source is used by the ITM / TPIU peripheral.

I don't have binary traces but [these tests](https://github.com/rust-embedded/itm/blob/master/src/tests.rs) have some example packets.

> only about 20% of data seems to be valid.

One thing I have run into before when decoding ITM packets is that there's some configuration bit in one of the related peripherals (TPIU something?) that adds some sort of framing / encoding on top of the ITM packets that when read through SWO makes the data stream *mostly* unparseable (according to the linked spec) even if the frequency is correct. Toggling that bit makes the `itm` decoder work.

Unfortunately I don't remember which register it was -- I have not used these tools in a while -- and to get this bit of information I had to go through some older revisions of documents as the bitfield is not documented in recent revisions. I think [this configuration](https://github.com/rust-embedded/cortex-m/issues/82#issue-299792781) gets most of the settings right but I think it's still missing this framing / encoding bitfield I mentioned. I'll try to dig through some old code to see if I can spot this bit of info.

**Comment by japaric** [comment]
> I'll try to dig through some old code to see if I can spot this bit of info.

according to my notes: "disable (clear) ENFCONT bitfield (bit 1) in the TPIU_FFCR register"

> I think this configuration gets most of the settings right but I think it's still missing this framing / encoding bitfield I mentioned.

I correct myself then: the linked configuration should work. If you already have that, I would check the frequencies.

**Comment by g8ecj** [comment]
Excellent. Running on all cylinders now!!
I also had the Exception trace enabled in the DWT which was causing occasional overflows as well.
Now getting 146k samples/s from a 64MHz stm32f303 (SWO running @ 8Mb/s) and 382k samples/s from a 200Mhz stm32f779 (swo running @ 20Mb/s). 
Profiles, even over a short timeframe make sense now!
Interesting that sigrok (PulseView) manages to decode the exceptions OK but your code doesn't. Obviously different decoder libraries but there may be some clues there if you fell the urge ;)

**Comment by g8ecj** [comment]
I've now updated openocd (0.11.0-3) and gdb (10.3.1.2-2.3) to the latest xpack versions https://xpack.github.io/ and everything now works as expected including using the st-link SWV input and outputting data to a fifo. 
Still using sigrok for any captures over 2Mb but having explored the limitations I'm more than happy with it.
