### ISSUE TITLE
Notice: replacement crate(s) in development

### ISSUE THREAD

**Issue by tmplt** [japaric/itm-tools#2]
I do not know what the development status of this repo is, but replacement crates are in progress at https://github.com/rtic-scope/itm. They are published as `itm` and `itm-decode` on the crate registery (not up-to-date due to unreleased dependencies). The `itm` library decodes the whole ITM specification and `itm-decode` is planned to reach feature parity with this repository.

`itm` and `itm-decode` may eventually be adopted into the Embedded Rust WG. See also https://github.com/rust-embedded/wg/blob/master/rfcs/0589-move-itm-crate.md.

**Comment by japaric** [comment]
Great work on rtic-scope! I no longer work with the code in this repo. I'll link to the rtic-scope org from the README. Thanks for letting me know.
